(maint) Bump maximum Puppet version to include 7.x, prep for release
puppetlabs/puppetlabs-gcloud_inventory pull request #10
Opened 2021-01-21 19:22 UTC by lucywyman

2021-01-21 19:23 UTC, beechtom approved these changes

2021-01-21 19:24 UTC, beechtom requested changes
Looks like we'll need to make the same Rubocop changes here that were added to puppetlabs/puppetlabs-ruby_task_helper

2021-01-21 19:25 UTC, lucywyman commented
Yeah this is exactly the kind of thing I was hoping to catch!

2021-01-22 17:06 UTC, beechtom approved these changes

2021-01-22 17:08 UTC, merged